function fixCreativeTypes(className, deobfName, code)
{
  add(className, deobfName, CLIENT, "Adding/fixing subtypes in creative",
  function(cn)
  {
    for (var i = 0; i < cn.methods.size(); i++)
    {
      mn = cn.methods.get(i);
      if (mn.name + mn.desc == "a(ILve;Ljava/util/List;)V")
      {
        cn.methods.remove(mn);
      }
    }
    var mn = MethodNode(ACC_PUBLIC, "a", "(ILve;Ljava/util/List;)V", null, null);
    mn.instructions.add(toInsnList(code));
    cn.methods.add(mn);
  });
}
function skipIfHoldingSwordInCreative(mn)
{
  var label = LabelNode();
  return CodeInserter(
    BeginningFinder(),
    [
      VarInsnNode(ALOAD, 0),
      FieldInsnNode(GETFIELD, "bdr", "k", "Laaj;"),
      MethodInsnNode(INVOKEVIRTUAL, "aaj", "d", "()Z"),
      JumpInsnNode(IFEQ, label),
      VarInsnNode(ALOAD, 0),
      FieldInsnNode(GETFIELD, "bdr", "a", "Lnet/minecraft/client/Minecraft;"),
      FieldInsnNode(GETFIELD, "net/minecraft/client/Minecraft", "g", "Lbdv;"),
      MethodInsnNode(INVOKEVIRTUAL, "bdv", "bG", "()Lwm;"),
      JumpInsnNode(IFNULL, label),
      VarInsnNode(ALOAD, 0),
      FieldInsnNode(GETFIELD, "bdr", "a", "Lnet/minecraft/client/Minecraft;"),
      FieldInsnNode(GETFIELD, "net/minecraft/client/Minecraft", "g", "Lbdv;"),
      MethodInsnNode(INVOKEVIRTUAL, "bdv", "bG", "()Lwm;"),
      MethodInsnNode(INVOKEVIRTUAL, "wm", "b", "()Lwk;"),
      TypeInsnNode(INSTANCEOF, "xr"),
      JumpInsnNode(IFEQ, label),
      InsnNode(RETURN),
      label,
      FrameNode(F_SAME, 0, null, 0, null),
    ],
    INSERT_BEFORE
  ).process(mn);
}

function getOreTypesCode()
{
  var l0 = LabelNode();
  return [
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_0),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ILOAD, 1),
    FieldInsnNode(GETSTATIC, "apa", "ct", "Lapa;"),
    FieldInsnNode(GETFIELD, "apa", "cz", "I"),
    JumpInsnNode(IF_ICMPEQ, l0),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_1),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_2),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    l0,
    FrameNode(F_SAME, 0, null, 0, null),
    InsnNode(RETURN),
  ];
}
fixCreativeTypes("ans", "BlockOre", getOreTypesCode());
fixCreativeTypes("aof", "BlockRedstoneOre", getOreTypesCode());
fixCreativeTypes("FCBlockAestheticNonOpaque", null,
[
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  InsnNode(ICONST_5),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 10),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 12),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  InsnNode(RETURN),
]);
fixCreativeTypes("FCBlockMouldingAndDecorative", null,
[
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  InsnNode(ICONST_0),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 12),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 13),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 15),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  InsnNode(RETURN),
]);
fixCreativeTypes("FCBlockPlanter", null,
[
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  InsnNode(ICONST_0),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  InsnNode(ICONST_1),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  InsnNode(ICONST_2),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 8),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 9),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  InsnNode(RETURN),
]);
function getWoodTypesCode()
{
  var l0 = LabelNode();
  var l1 = LabelNode();
  return [
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_0),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_1),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_2),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_3),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ILOAD, 1),
    FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodBirchMouldingAndDecorative", "Lapa;"),
    FieldInsnNode(GETFIELD, "apa", "cz", "I"),
    JumpInsnNode(IF_ICMPNE, l0),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_4),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_5),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 6),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 7),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 8),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 9),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 10),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 11),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    FieldInsnNode(GETSTATIC, "GPEBTWTweak", "btwBloodPlanks", "Z"),
    JumpInsnNode(IFEQ, l0),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 16),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 20),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 24),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    l0,
    FrameNode(F_SAME, 0, null, 0, null),
    VarInsnNode(ILOAD, 1),
    FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodJungleSidingAndCorner", "Lapa;"),
    FieldInsnNode(GETFIELD, "apa", "cz", "I"),
    JumpInsnNode(IF_ICMPNE, l1),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    InsnNode(ICONST_5),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 6),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 7),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    FieldInsnNode(GETSTATIC, "GPEBTWTweak", "btwBloodPlanks", "Z"),
    JumpInsnNode(IFEQ, l1),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 16),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    VarInsnNode(ALOAD, 3),
    TypeInsnNode(NEW, "wm"),
    InsnNode(DUP),
    VarInsnNode(ILOAD, 1),
    InsnNode(ICONST_1),
    IntInsnNode(BIPUSH, 20),
    MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
    MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
    InsnNode(POP),
    l1,
    FrameNode(F_SAME, 0, null, 0, null),
    InsnNode(RETURN),
  ];
}
fixCreativeTypes("FCBlockWoodMouldingAndDecorative", null, getWoodTypesCode());
fixCreativeTypes("FCBlockWoodSidingAndCornerAndDecorative", null, getWoodTypesCode());
fixCreativeTypes("FCBlockAestheticOpaqueEarth", null,
[
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 6),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  VarInsnNode(ALOAD, 3),
  TypeInsnNode(NEW, "wm"),
  InsnNode(DUP),
  VarInsnNode(ILOAD, 1),
  InsnNode(ICONST_1),
  IntInsnNode(BIPUSH, 7),
  MethodInsnNode(INVOKESPECIAL, "wm", "<init>", "(III)V"),
  MethodInsnNode(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z"),
  InsnNode(POP),
  InsnNode(RETURN),
]);
function fixWoodBlockPick(cn)
{
  var l0 = LabelNode();
  var l1 = LabelNode();
  var l2 = LabelNode();
  var l3 = LabelNode();
  var l4 = LabelNode();
  var l5 = LabelNode();
  var l6 = LabelNode();
  var l7 = LabelNode();
  var l8 = LabelNode();
  var l9 = LabelNode();
  var l10 = LabelNode();
  var l11 = LabelNode();
  var l12 = LabelNode();
  var l13 = LabelNode();
  var l14 = LabelNode();
  var l15 = LabelNode();
  var l16 = LabelNode();
  var l17 = LabelNode();
  var l18 = LabelNode();
  var l19 = LabelNode();
  var l20 = LabelNode();
  var l21 = LabelNode();
  var l22 = LabelNode();
  var l23 = LabelNode();
  var l24 = LabelNode();
  var l25 = LabelNode();
  var l26 = LabelNode();
  var l27 = LabelNode();
  var l28 = LabelNode();
  var l29 = LabelNode();
  var l30 = LabelNode();
  var l31 = LabelNode();
  var l32 = LabelNode();
  var l33 = LabelNode();
  var mn = MethodNode(ACC_PUBLIC, "h", "(Laab;III)I", null, null);
  mn.instructions.add(toInsnList(
    [
      VarInsnNode(ALOAD, 1),
      VarInsnNode(ILOAD, 2),
      VarInsnNode(ILOAD, 3),
      VarInsnNode(ILOAD, 4),
      MethodInsnNode(INVOKEVIRTUAL, "aab", "a", "(III)I"),
      VarInsnNode(ISTORE, 5),
      VarInsnNode(ALOAD, 1),
      VarInsnNode(ILOAD, 2),
      VarInsnNode(ILOAD, 3),
      VarInsnNode(ILOAD, 4),
      MethodInsnNode(INVOKEVIRTUAL, "aab", "h", "(III)I"),
      VarInsnNode(ISTORE, 6),
      VarInsnNode(ILOAD, 5),
      FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodOakMouldingAndDecorative", "Lapa;"),
      FieldInsnNode(GETFIELD, "apa", "cz", "I"),
      JumpInsnNode(IF_ICMPNE, l0),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 15),
      JumpInsnNode(IF_ICMPNE, l1),
      IntInsnNode(BIPUSH, 8),
      JumpInsnNode(GOTO, l2),
      l1,
      FrameNode(F_APPEND, 2, [INTEGER, INTEGER], 0, null),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 13),
      JumpInsnNode(IF_ICMPLT, l3),
      InsnNode(ICONST_4),
      JumpInsnNode(GOTO, l2),
      l3,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_0),
      l2,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l0,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 5),
      FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodSpruceMouldingAndDecorative", "Lapa;"),
      FieldInsnNode(GETFIELD, "apa", "cz", "I"),
      JumpInsnNode(IF_ICMPNE, l4),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 15),
      JumpInsnNode(IF_ICMPNE, l5),
      IntInsnNode(BIPUSH, 9),
      JumpInsnNode(GOTO, l6),
      l5,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 13),
      JumpInsnNode(IF_ICMPLT, l7),
      InsnNode(ICONST_5),
      JumpInsnNode(GOTO, l6),
      l7,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_1),
      l6,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l4,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 5),
      FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodSpruceSidingAndCorner", "Lapa;"),
      FieldInsnNode(GETFIELD, "apa", "cz", "I"),
      JumpInsnNode(IF_ICMPNE, l8),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 14),
      JumpInsnNode(IF_ICMPNE, l9),
      InsnNode(ICONST_5),
      JumpInsnNode(GOTO, l10),
      l9,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_1),
      l10,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l8,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 5),
      FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodBirchMouldingAndDecorative", "Lapa;"),
      FieldInsnNode(GETFIELD, "apa", "cz", "I"),
      JumpInsnNode(IF_ICMPNE, l11),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 15),
      JumpInsnNode(IF_ICMPNE, l12),
      IntInsnNode(BIPUSH, 10),
      JumpInsnNode(GOTO, l13),
      l12,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 13),
      JumpInsnNode(IF_ICMPLT, l14),
      IntInsnNode(BIPUSH, 6),
      JumpInsnNode(GOTO, l13),
      l14,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_2),
      l13,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l11,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 5),
      FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodBirchSidingAndCorner", "Lapa;"),
      FieldInsnNode(GETFIELD, "apa", "cz", "I"),
      JumpInsnNode(IF_ICMPNE, l15),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 14),
      JumpInsnNode(IF_ICMPNE, l16),
      IntInsnNode(BIPUSH, 6),
      JumpInsnNode(GOTO, l17),
      l16,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_2),
      l17,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l15,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 5),
      FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodJungleMouldingAndDecorative", "Lapa;"),
      FieldInsnNode(GETFIELD, "apa", "cz", "I"),
      JumpInsnNode(IF_ICMPNE, l18),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 15),
      JumpInsnNode(IF_ICMPNE, l19),
      IntInsnNode(BIPUSH, 11),
      JumpInsnNode(GOTO, l20),
      l19,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 13),
      JumpInsnNode(IF_ICMPLT, l21),
      IntInsnNode(BIPUSH, 7),
      JumpInsnNode(GOTO, l20),
      l21,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_3),
      l20,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l18,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 5),
      FieldInsnNode(GETSTATIC, "FCBetterThanWolves", "fcBlockWoodJungleSidingAndCorner", "Lapa;"),
      FieldInsnNode(GETFIELD, "apa", "cz", "I"),
      JumpInsnNode(IF_ICMPNE, l22),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 14),
      JumpInsnNode(IF_ICMPNE, l23),
      IntInsnNode(BIPUSH, 7),
      JumpInsnNode(GOTO, l24),
      l23,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_3),
      l24,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l22,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 5),
      IntInsnNode(SIPUSH, 1008),
      JumpInsnNode(IF_ICMPNE, l25),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 15),
      JumpInsnNode(IF_ICMPNE, l26),
      IntInsnNode(BIPUSH, 24),
      JumpInsnNode(GOTO, l27),
      l26,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 13),
      JumpInsnNode(IF_ICMPLT, l28),
      IntInsnNode(BIPUSH, 20),
      JumpInsnNode(GOTO, l27),
      l28,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 12),
      JumpInsnNode(IF_ICMPNE, l29),
      IntInsnNode(BIPUSH, 16),
      JumpInsnNode(GOTO, l27),
      l29,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_4),
      l27,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l25,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 5),
      IntInsnNode(SIPUSH, 1007),
      JumpInsnNode(IF_ICMPNE, l30),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 14),
      JumpInsnNode(IF_ICMPNE, l31),
      IntInsnNode(BIPUSH, 20),
      JumpInsnNode(GOTO, l32),
      l31,
      FrameNode(F_SAME, 0, null, 0, null),
      VarInsnNode(ILOAD, 6),
      IntInsnNode(BIPUSH, 12),
      JumpInsnNode(IF_ICMPNE, l33),
      IntInsnNode(BIPUSH, 16),
      JumpInsnNode(GOTO, l32),
      l33,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_4),
      l32,
      FrameNode(F_SAME1, 0, null, 1, [INTEGER]),
      InsnNode(IRETURN),
      l30,
      FrameNode(F_SAME, 0, null, 0, null),
      InsnNode(ICONST_0),
      InsnNode(IRETURN),
    ]
  ));
  cn.methods.add(mn);
}
add("FCBlockWoodMouldingAndDecorative", null, CLIENT, "Fixing block middle-click picking", fixWoodBlockPick);
add("FCBlockWoodSidingAndCornerAndDecorative", null, CLIENT, "Fixing block middle-click picking", fixWoodBlockPick);

tweak("ayy", "GuiContainerCreative", CLIENT, "i()V", 0xB6582FB7, "Replacing enchanted books with scrolls",
function(mn)
{
  for (var i = 0; i < mn.instructions.size(); i++)
  {
    var n = mn.instructions.get(i);
    if (isInstance(n, "org.objectweb.asm.tree.MethodInsnNode") && n.owner.equals("vw") && n.name.equals("a") && n.desc.equals("(Lyz;Ljava/util/List;)V"))
    {
      n.opcode = INVOKESTATIC;
      n.owner = "GPEBTWTweak";
      n.name = "addCreativeEnchantment";
      mn.instructions.insert(n, toInsnList(
        [
          InsnNode(POP),
        ]
      ));
      return true;
    }
  }
});
tweak("bdr", "PlayerControllerMP", CLIENT, "b(IIII)V", 0xC6374240, "(1/2) Fix swords breaking blocks in creative",
skipIfHoldingSwordInCreative);
tweak("bdr", "PlayerControllerMP", CLIENT, "c(IIII)V", 0xE96B41E3, "(2/2) Fix swords breaking blocks in creative",
skipIfHoldingSwordInCreative);
